version: "3.4"
services:
  demo:
    build: .
    volumes:
      - ./tmp:/app/tmp/:delegated
    ports:
      - "80:80"
    environment:
      - DATABASE_URL
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - API_ACCESS_KEY

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

